# Generated by Django 3.2.4 on 2021-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projectapp', '0002_campregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='campregister',
            name='Campname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
